api = "0.8"

[buildpack]
id = "siestacat/crontab"
name = "Crontab"
version = "0.0.1"
keywords = ["crontab", "cronjob", "crond"]
description = "Install crontab contents from file"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
id = "*"